# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7539482cda62f4f5363966aaea36548dba8e6014db6c0bf2d1b4886386fe9b3320054d4296a1fb169020ee8a3296928173ebb9188bc53918607b2a3cddedba7c

test:
  secret_key_base: dbc68cd849dbd1e64001b43843c42e4958cc57c59d2c93f019d15592a6670fb6894bb22f83a7456f67ed0ea6d79c2928e3650f019e8b1f34c319611b6d24a875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
